version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"  # Porta do Jenkins
      - "50000:50000" # Comunicação entre agentes
    environment:
      - JENKINS_USER=admin
      - JENKINS_PASS=admin
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Permite execução de containers pelo Jenkins
      - ./jenkinsfile:/var/jenkins_home/workspace/jenkinsfile  # Passa o Jenkinsfile já estruturado
    networks:
      - jenkins_net

volumes:
  jenkins_home:

networks:
  jenkins_net:
    driver: bridge
